# Train plant diseases detection

## Importing Libraries

In [1]:
import tensorflow as tf
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

## Data Preprocessing

### Training Image Preprocessing

In [35]:
training_set = tf.keras.utils.image_dataset_from_directory(
    'train', # directory 
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False
)

Found 69768 files belonging to 38 classes.


In [36]:
training_set

<_PrefetchDataset element_spec=(TensorSpec(shape=(None, 128, 128, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None, 38), dtype=tf.float32, name=None))>

In [37]:
# x, y 
for x, y in training_set:
    print("x : " , x , x.shape)
    print("y : " , y , y.shape)
    break

    # x: images: 
    # shape=(32, 128, 128, 3), dtype=float32) (32, 128, 128, 3)
    # y : Classes: 
    # shape=(32, 38), dtype=float32) (32, 38)

x :  tf.Tensor(
[[[[ 85.25  93.25 130.25]
   [ 82.75  90.75 127.75]
   [ 81.5   89.5  126.5 ]
   ...
   [ 86.    92.   128.  ]
   [ 84.25  90.25 126.25]
   [ 90.75  96.75 132.75]]

  [[ 84.    92.   129.  ]
   [ 83.25  91.25 128.25]
   [ 85.25  93.25 130.25]
   ...
   [ 91.75  97.75 133.75]
   [ 90.    96.   132.  ]
   [ 81.25  87.25 123.25]]

  [[ 87.25  95.25 132.25]
   [ 87.75  95.75 132.75]
   [ 87.5   95.5  132.5 ]
   ...
   [ 87.    93.   129.  ]
   [ 83.    89.   125.  ]
   [ 90.5   96.5  132.5 ]]

  ...

  [[154.25 170.25 204.25]
   [153.5  169.5  203.5 ]
   [154.75 170.75 204.75]
   ...
   [137.25 153.25 189.25]
   [133.25 149.25 185.25]
   [130.   146.   182.  ]]

  [[156.25 172.25 206.25]
   [154.75 170.75 204.75]
   [152.75 168.75 202.75]
   ...
   [136.5  152.5  188.5 ]
   [137.25 153.25 189.25]
   [136.5  152.5  188.5 ]]

  [[154.25 170.25 204.25]
   [155.75 171.75 205.75]
   [157.   173.   207.  ]
   ...
   [138.25 154.25 190.25]
   [137.75 153.75 189.75]
   [136.75 152.

### Validation Image Preprocessing

In [40]:
validation_set = tf.keras.utils.image_dataset_from_directory(
    'valid', # directory 
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False
)

Found 17452 files belonging to 38 classes.


In [41]:
validation_set

<_PrefetchDataset element_spec=(TensorSpec(shape=(None, 128, 128, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None, 38), dtype=tf.float32, name=None))>

## Building Model

In [42]:
# from tensorflow.keras.layers import Dense,Conv2D, MaxPool2D, Flatten
# from tensorflow.keras.models import Sequential

In [43]:
layers = tf.keras.layers

In [44]:
cnn = tf.keras.models.Sequential()

In [45]:
cnn.add(layers.Conv2D(filters=32,kernel_size=3,padding='same',activation='relu',input_shape=[128,128,3]))
cnn.add(layers.Conv2D(filters=32,kernel_size=3,activation='relu'))
cnn.add(layers.MaxPool2D(pool_size=2,strides=2))

In [46]:
cnn.add(layers.Conv2D(filters=64,kernel_size=3,padding='same',activation='relu'))
cnn.add(layers.Conv2D(filters=64,kernel_size=3,activation='relu'))
cnn.add(layers.MaxPool2D(pool_size=2,strides=2))

In [47]:
cnn.add(layers.Conv2D(filters=128,kernel_size=3,padding='same',activation='relu'))
cnn.add(layers.Conv2D(filters=128,kernel_size=3,activation='relu'))
cnn.add(layers.MaxPool2D(pool_size=2,strides=2))

In [48]:
cnn.add(layers.Conv2D(filters=256,kernel_size=3,padding='same',activation='relu'))
cnn.add(layers.Conv2D(filters=256,kernel_size=3,activation='relu'))
cnn.add(layers.MaxPool2D(pool_size=2,strides=2))

In [49]:
cnn.add(layers.Conv2D(filters=512,kernel_size=3,padding='same',activation='relu'))
cnn.add(layers.Conv2D(filters=512,kernel_size=3,activation='relu'))
cnn.add(layers.MaxPool2D(pool_size=2,strides=2))

In [50]:
cnn.add(layers.Flatten())

In [51]:
# Hidden Layer to feed fully connected layers
cnn.add(layers.Dense(units=1024, activation = 'relu'))

In [52]:
# Output Layer: 38 as we have 38 class
cnn.add(layers.Dense(units=38, activation = 'softmax'))

### Compiling the Model

In [53]:
cnn.compile(optimizer="adam", loss="categorical_crossentropy", metrics=['accuracy'])

In [54]:
cnn.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ conv2d_20 (Conv2D)                   │ (None, 128, 128, 32)        │             896 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_21 (Conv2D)                   │ (None, 126, 126, 32)        │           9,248 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_10 (MaxPooling2D)      │ (None, 63, 63, 32)          │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_22 (Conv2D)                   │ (None, 63, 63, 64)          │          18,496 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_23 (Conv2D)                   │ (None, 61, 61, 64)          │          36,928 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_11 (MaxPooling2D)      │ (None, 30, 30, 64)          │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_24 (Conv2D)                   │ (None, 30, 30, 128)         │          73,856 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_25 (Conv2D)                   │ (None, 28, 28, 128)         │         147,584 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_12 (MaxPooling2D)      │ (None, 14, 14, 128)         │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_26 (Conv2D)                   │ (None, 14, 14, 256)         │         295,168 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_27 (Conv2D)                   │ (None, 12, 12, 256)         │         590,080 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_13 (MaxPooling2D)      │ (None, 6, 6, 256)           │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_28 (Conv2D)                   │ (None, 6, 6, 512)           │       1,180,160 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_29 (Conv2D)                   │ (None, 4, 4, 512)           │       2,359,808 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_14 (MaxPooling2D)      │ (None, 2, 2, 512)           │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten_1 (Flatten)                  │ (None, 2048)                │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 1024)                │       2,098,176 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 38)                  │          38,950 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 6,849,350 (26.13 MB)

 Trainable params: 6,849,350 (26.13 MB)

 Non-trainable params: 0 (0.00 B)

## Training Model

In [ ]:
training_history = cnn.fit(x= training_set, validation_data= validation_set, epochs= 10)

Epoch 1/10
  59/2181 ━━━━━━━━━━━━━━━━━━━━ 47:09 1s/step - accuracy: 0.0340 - loss: 4.6561